<?php

use App\Http\Controllers\CherkasyNewsController;
use App\Http\Controllers\ChernihivNewsController;
use App\Http\Controllers\ChernivtsiNewsController;
use App\Http\Controllers\CookieConsentController;
use App\Http\Controllers\CorporationController;
use App\Http\Controllers\DniproNewsController;
use App\Http\Controllers\HarkivNewsController;
use App\Http\Controllers\HmelnytskiyNewsController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\IvanoFrankivskNewsController;
use App\Http\Controllers\KhersonNewsController;
use App\Http\Controllers\KirovogradNewsController;
use App\Http\Controllers\KyivNewsController;
use App\Http\Controllers\LineNewsController;
use App\Http\Controllers\LvivNewsController;
use App\Http\Controllers\MykolayivNewsController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\NewsTodayController;
use App\Http\Controllers\OdesaNewsController;
use App\Http\Controllers\Payment\PaymentController;
use App\Http\Controllers\PoltavaNewsController;
use App\Http\Controllers\RivneNewsController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SectionsController;
use App\Http\Controllers\SumyNewsController;
use App\Http\Controllers\TernopilNewsController;
use App\Http\Controllers\VinnytsaNewsController;
use App\Http\Controllers\VolynskNewsController;
use App\Http\Controllers\ZakarpatskNewsController;
use App\Http\Controllers\ZaporizhzhiaNewsController;
use App\Http\Controllers\ZhytomyrNewsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomepageController::class, 'index'])->name('homepage.index');

Route::post('/accept-cookies', [CookieConsentController::class, 'setCookieAndAccept'])->name('accept-cookies');
Route::post('/cookie/revoke', 'CookieConsentController@revokeCookie')->name('cookie.revoke');

Route::get('/subscription/year', [PaymentController::class, 'createYearSubsciption'])->name('subscription.year');
Route::get('/subscription/month', [PaymentController::class, 'createMonthSubsciption'])->name('subscription.month');

Route::get('/news/{url}', [NewsController::class, 'index'])->name('news.index');
Route::get('/news-today', [NewsTodayController::class, 'index'])->name('news-today.index');
Route::get('/news', [LineNewsController::class, 'index'])->name('news.line');
Route::get('/search', [SearchController::class, 'index'])->name('search.index');

// Sections
Route::get('/usa', [SectionsController::class, 'usa'])->name('usa.index');
Route::get('/vijna', [SectionsController::class, 'vijna'])->name('vijna.index');
Route::get('/europe', [SectionsController::class, 'europe'])->name('europe.index');
Route::get('/china', [SectionsController::class, 'china'])->name('china.index');
Route::get('/suspilstvo', [SectionsController::class, 'suspilstvo'])->name('suspilstvo.index');
Route::get('/biznes', [SectionsController::class, 'biznes'])->name('biznes.index');
Route::get('/polityka', [SectionsController::class, 'polityka'])->name('polityka.index');
Route::get('/ekonomika', [SectionsController::class, 'ekonomika'])->name('ekonomika.index');
Route::get('/analityka', [SectionsController::class, 'analityka'])->name('analityka.index');
Route::get('/technologies', [SectionsController::class, 'technologies'])->name('technologies.index');
Route::get('/nauka', [SectionsController::class, 'nauka'])->name('nauka.index');
Route::get('/kultura', [SectionsController::class, 'kultura'])->name('kultura.index');
Route::get('/ekolohiia', [SectionsController::class, 'ekolohiia'])->name('ekolohiia.index');
Route::get('/finance', [SectionsController::class, 'finance'])->name('finance.index');
Route::get('/vlada', [SectionsController::class, 'vlada'])->name('vlada.index');
Route::get('/sport', [SectionsController::class, 'sport'])->name('sport.index');
Route::get('/history', [SectionsController::class, 'history'])->name('history.index');
Route::get('/pryhody', [SectionsController::class, 'pryhody'])->name('pryhody.index');
Route::get('/musick', [SectionsController::class, 'musick'])->name('musick.index');
Route::get('/fashion', [SectionsController::class, 'fashion'])->name('fashion.index');
Route::get('/kino', [SectionsController::class, 'kino'])->name('kino.index');
Route::get('/interviu', [SectionsController::class, 'interviu'])->name('interviu.index');
Route::get('/dumky', [SectionsController::class, 'dumky'])->name('dumky.index');
Route::get('/auto', [SectionsController::class, 'auto'])->name('auto.index');
Route::get('/ihry', [SectionsController::class, 'ihry'])->name('ihry.index');
Route::get('/education', [SectionsController::class, 'education'])->name('education.index');
Route::get('/kulinariia', [SectionsController::class, 'kulinariia'])->name('kulinariia.index');
Route::get('/health', [SectionsController::class, 'health'])->name('health.index');
Route::get('/parenting', [SectionsController::class, 'parenting'])->name('parenting.index');
Route::get('/real-estate', [SectionsController::class, 'real_estate'])->name('real-estate.index');
Route::get('/traveling', [SectionsController::class, 'traveling'])->name('traveling.index');
Route::get('/svitovi-novyny', [SectionsController::class, 'svitovi_novyny'])->name('svitovi-novyny.index');
Route::get('/north-america', [SectionsController::class, 'north_america'])->name('north-america.index');
Route::get('/south-america', [SectionsController::class, 'south_america'])->name('south-america.index');
Route::get('/middle-east', [SectionsController::class, 'middle_east'])->name('middle-east.index');
Route::get('/pacific-region', [SectionsController::class, 'pacific_region'])->name('pacific-region.index');
Route::get('/africa', [SectionsController::class, 'africa'])->name('africa.index');
Route::get('/pres-reliz', [SectionsController::class, 'pres_reliz'])->name('pres-reliz.index');
Route::get('/ofitsijno', [SectionsController::class, 'ofitsijno'])->name('ofitsijno.index');
Route::get('/novyny-biznesu', [SectionsController::class, 'novyny_biznesu'])->name('novyny-biznesu.index');
Route::get('/politychni-novyny', [SectionsController::class, 'politychni_novyny'])->name('politychni-novyny.index');

// Corporation Section
Route::get('/corporate-section', [CorporationController::class, 'corporate_section'])->name('corporate_section.index');
Route::get('/politics', [CorporationController::class, 'politics'])->name('politics.index');
Route::get('/legal-information', [CorporationController::class, 'legal_information'])->name('legal_information.index');
Route::get('/more-about-us', [CorporationController::class, 'more_about_us'])->name('more_about_us.index');
Route::get('/about-us', [CorporationController::class, 'about_us'])->name('about_us.index');
Route::get('/maps-ua', [CorporationController::class, 'maps_ua'])->name('maps_ua.index');
Route::get('/advertising', [CorporationController::class, 'advertising'])->name('advertising.index');
Route::get('/partnership', [CorporationController::class, 'partnership'])->name('partnership.index');
Route::get('/work-with-us', [CorporationController::class, 'work_with_us'])->name('work_with_us.index');
Route::get('/editorship', [CorporationController::class, 'editorship'])->name('editorship.index');
Route::get('/subscription', [CorporationController::class, 'subscription'])->name('subscription.index');
Route::get('/privacy-politics', [CorporationController::class, 'privacy_politics'])->name('privacy_politics.index');
Route::get('/editorial-politics', [CorporationController::class, 'editorial_politics'])->name('editorial_politics.index');
Route::get('/cookie-politics', [CorporationController::class, 'cookie_politics'])->name('cookie_politics.index');
Route::get('/service', [CorporationController::class, 'service'])->name('service.index');
Route::get('/content', [CorporationController::class, 'content'])->name('content.index');
Route::get('/terms-of-sale', [CorporationController::class, 'terms_of_sale'])->name('terms_of_sale.index');
Route::get('/comments-section', [CorporationController::class, 'comments_section'])->name('comments_section.index');
Route::get('/presentation-for-readers', [CorporationController::class, 'presentation_for_readers'])->name('presentation_for_readers.index');
Route::get('/social-responsability', [CorporationController::class, 'social_responsability'])->name('social_responsability.index');
Route::get('/journalist', [CorporationController::class, 'journalist'])->name('journalist.index');


Route::get('/{city}', [HomepageController::class, 'feed'])->name('city.feed');
Route::get('/{city}/news', [LineNewsController::class, 'index']);
Route::get('/{city}/news/{url}', [NewsController::class, 'getFeedNews']);

// Vinnytsa
Route::get('/vinnytsa', [VinnytsaNewsController::class, 'vinnytsaHome'])->name('vinnytsa.news');
Route::get('/vinnytsa/news', [VinnytsaNewsController::class, 'vinnytsaHome'])->name('vinnytsa.line');
Route::get('/vinnytsa/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('vinnytsa.news');
Route::get('/zhmerynka', [VinnytsaNewsController::class, 'zhmerynkaHome'])->name('zhmerynka.news');
Route::get('/zhmerynka/news', [LineNewsController::class, 'zhmerynkaHome'])->name('zhmerynka.line');
Route::get('/zhmerynka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('zhmerynka.news');
Route::get('/mohyliv-podilskyi', [VinnytsaNewsController::class, 'mohylivPodilskyiHome'])->name('mohyliv-podilskyi.news');
Route::get('/mohyliv-podilskyi/news', [VinnytsaNewsController::class, 'mohylivPodilskyiHome'])->name('mohyliv-podilskyi.line');
Route::get('/mohyliv-podilskyi/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('mohyliv-podilskyi.news');
Route::get('/hmilnyk', [VinnytsaNewsController::class, 'hmilnykHome'])->name('hmilnyk.news');
Route::get('/hmilnyk/news', [VinnytsaNewsController::class, 'hmilnykHome'])->name('hmilnyk.line');
Route::get('/hmilnyk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('hmilnyk.news');
Route::get('/gaysin', [VinnytsaNewsController::class, 'gaysinHome'])->name('gaysin.news');
Route::get('/gaysin/news', [VinnytsaNewsController::class, 'gaysinHome'])->name('gaysin.line');
Route::get('/gaysin/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('gaysin.news');
Route::get('/kozyatyn', [VinnytsaNewsController::class, 'koziatynHome'])->name('kozyatyn.news');
Route::get('/kozyatyn/news', [VinnytsaNewsController::class, 'koziatynHome'])->name('kozyatyn.line');
Route::get('/kozyatyn/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kozyatyn.news');
Route::get('/ladyzhin', [VinnytsaNewsController::class, 'ladyzhynHome'])->name('ladyzhin.news');
Route::get('/ladyzhin/news', [VinnytsaNewsController::class, 'ladyzhynHome'])->name('ladyzhin.line');
Route::get('/ladyzhin/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('ladyzhin.news');

//Kyiv
Route::get('/kyiv/news/', [KyivNewsController::class, 'kyivLine'])->name('kyiv.line');
Route::get('/kyiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kyiv.news');
Route::get('/berezan/news', [DniproNewsController::class, 'dniproNews'])->name('berezan.line');
Route::get('/berezan/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('berezan.news');
Route::get('/bilacerkva/news/', [KyivNewsController::class, 'bilacerkvaLine'])->name('bilacerkva.line');
Route::get('/bilacerkva/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('bilacerkva.news');
Route::get('/boryspil/news/', [KyivNewsController::class, 'boryspilLine'])->name('boryspil.line');
Route::get('/boryspil/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('boryspil.news');
Route::get('/boyarka/news/', [KyivNewsController::class, 'boyarkaLine'])->name('boyarka.line');
Route::get('/boyarka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('boyarka.news');
Route::get('/brovary/news/', [KyivNewsController::class, 'brovaryLine'])->name('brovary.line');
Route::get('/brovary/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('brovary.news');
Route::get('/bucha/news/', [KyivNewsController::class, 'buchaLine'])->name('bucha.line');
Route::get('/bucha/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('bucha.news');
Route::get('/fastiv/news/', [KyivNewsController::class, 'fastivLine'])->name('fastiv.line');
Route::get('/fastiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('fastiv.news');
Route::get('/irpin/news/', [KyivNewsController::class, 'irpinLine'])->name('irpin.line');
Route::get('/irpin/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('irpin.news');
Route::get('/obukhiv/news/', [KyivNewsController::class, 'obukhivLine'])->name('obukhiv.line');
Route::get('/obukhiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('obukhiv.news');
Route::get('/pereyaslav/news/', [KyivNewsController::class, 'pereyaslavLine'])->name('pereyaslav.line');
Route::get('/pereyaslav/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('pereyaslav.news');
Route::get('/skvyra/news/', [KyivNewsController::class, 'skvyraLine'])->name('skvyra.line');
Route::get('/skvyra/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('skvyra.news');
Route::get('/slavutych/news/', [KyivNewsController::class, 'slavutychLine'])->name('slavutych.line');
Route::get('/slavutych/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('slavutych.news');
Route::get('/vasylkiv/news/', [KyivNewsController::class, 'vasylkivLine'])->name('vasylkiv.line');
Route::get('/vasylkiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('vasylkiv.news');
Route::get('/vyshhorod/news/', [KyivNewsController::class, 'vyshhorodLine'])->name('vyshhorod.line');
Route::get('/vyshhorod/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('vyshhorod.news');
Route::get('/vyshneve/news/', [KyivNewsController::class, 'vyshneveLine'])->name('vyshneve.line');
Route::get('/vyshneve/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('vyshneve.news');
Route::get('/yagotyn/news/', [KyivNewsController::class, 'yagotynLine'])->name('yagotyn.line');
Route::get('/yagotyn/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('yagotyn.news');

// Cherkasy
Route::get('/cherkasy', [CherkasyNewsController::class, 'cherkasyHome'])->name('cherkasy.news');
Route::get('/cherkasy/news', [CherkasyNewsController::class, 'cherkasyHome'])->name('cherkasy.line');
Route::get('/cherkasy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('cherkasy.news');
Route::get('/kaniv', [CherkasyNewsController::class, 'kanivHome'])->name('kaniv.news');
Route::get('/kaniv/news', [CherkasyNewsController::class, 'kanivHome'])->name('kaniv.line');
Route::get('/kaniv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kaniv.news');
Route::get('/smila', [CherkasyNewsController::class, 'smilaHome'])->name('smila.news');
Route::get('/smila/news', [CherkasyNewsController::class, 'smilaHome'])->name('smila.line');
Route::get('/smila/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('smila.news');
Route::get('/uman', [CherkasyNewsController::class, 'umanHome'])->name('uman.news');
Route::get('/uman/news', [CherkasyNewsController::class, 'umanHome'])->name('uman.line');
Route::get('/uman/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('uman.news');
Route::get('/vatutine', [CherkasyNewsController::class, 'vatutineHome'])->name('vatutine.news');
Route::get('/vatutine/news', [CherkasyNewsController::class, 'vatutineHome'])->name('vatutine.line');
Route::get('/vatutine/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('vatutine.news');
Route::get('/zolotonosha', [CherkasyNewsController::class, 'zolotonoshaHome'])->name('zolotonosha.news');
Route::get('/zolotonosha/news', [CherkasyNewsController::class, 'zolotonoshaHome'])->name('zolotonosha.line');
Route::get('/zolotonosha/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('zolotonosha.news');
Route::get('/zvenyhorodka', [CherkasyNewsController::class, 'zvenyhorodkaHome'])->name('zvenyhorodka.news');
Route::get('/zvenyhorodka/news', [CherkasyNewsController::class, 'zvenyhorodkaHome'])->name('zvenyhorodka.line');
Route::get('/zvenyhorodka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('zvenyhorodka.news');
// Chernihiv
Route::get('/bahmach', [ChernihivNewsController::class, 'bahmachHome'])->name('bahmach.news');
Route::get('/bahmach/news', [ChernihivNewsController::class, 'bahmachHome'])->name('bahmach.line');
Route::get('/bahmach/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('bahmach.news');
Route::get('/chernihiv', [ChernihivNewsController::class, 'chernihivHome'])->name('chernihiv.news');
Route::get('/chernihiv/news', [ChernihivNewsController::class, 'chernihivHome'])->name('chernihiv.line');
Route::get('/chernihiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('chernihiv.news');
Route::get('/nizhin', [ChernihivNewsController::class, 'nizhinHome'])->name('nizhin.news');
Route::get('/nizhin/news', [ChernihivNewsController::class, 'nizhinHome'])->name('nizhin.line');
Route::get('/nizhin/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('nizhin.news');
Route::get('/pryluki', [ChernihivNewsController::class, 'prylukiHome'])->name('pryluki.news');
Route::get('/pryluki/news', [ChernihivNewsController::class, 'prylukiHome'])->name('pryluki.line');
Route::get('/pryluki/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('pryluki.news');
// Chernivtsi
Route::get('/chernivtsi', [ChernivtsiNewsController::class, 'chernivtsiHome'])->name('chernivtsi.news');
Route::get('/chernivtsi/news', [ChernivtsiNewsController::class, 'chernivtsiHome'])->name('chernivtsi.line');
Route::get('/chernivtsi/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('chernivtsi.news');
// Harkiv
Route::get('/balaklia', [HarkivNewsController::class, 'balakliaHome'])->name('balaklia.news');
Route::get('/balaklia/news', [HarkivNewsController::class, 'balakliaHome'])->name('balaklia.line');
Route::get('/balaklia/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('balaklia.news');
Route::get('/chuguyiv', [HarkivNewsController::class, 'chuguyivHome'])->name('chuguyiv.news');
Route::get('/chuguyiv/news', [HarkivNewsController::class, 'chuguyivHome'])->name('chuguyiv.line');
Route::get('/chuguyiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('chuguyiv.news');
Route::get('/dergachi', [HarkivNewsController::class, 'dergachiHome'])->name('dergachi.news');
Route::get('/dergachi/news', [HarkivNewsController::class, 'dergachiHome'])->name('dergachi.line');
Route::get('/dergachi/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('dergachi.news');
Route::get('/harkiv', [HarkivNewsController::class, 'harkivHome'])->name('harkiv.news');
Route::get('/harkiv/news', [HarkivNewsController::class, 'harkivHome'])->name('harkiv.line');
Route::get('/harkiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('harkiv.news');
Route::get('/izum', [HarkivNewsController::class, 'izumHome'])->name('izum.news');
Route::get('/izum/news', [HarkivNewsController::class, 'izumHome'])->name('izum.line');
Route::get('/izum/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('izum.news');
Route::get('/krasnograd', [HarkivNewsController::class, 'krasnogradHome'])->name('krasnograd.news');
Route::get('/krasnograd/news', [HarkivNewsController::class, 'krasnogradHome'])->name('krasnograd.line');
Route::get('/krasnograd/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('krasnograd.news');
Route::get('/kupyansk', [HarkivNewsController::class, 'kupyanskHome'])->name('kupyansk.news');
Route::get('/kupyansk/news', [HarkivNewsController::class, 'kupyanskHome'])->name('kupyansk.line');
Route::get('/kupyansk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kupyansk.news');
Route::get('/lozova', [HarkivNewsController::class, 'lozovaHome'])->name('lozova.news');
Route::get('/lozova/news', [HarkivNewsController::class, 'lozovaHome'])->name('lozova.line');
Route::get('/lozova/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('lozova.news');
Route::get('/lubotin', [HarkivNewsController::class, 'lubotinHome'])->name('lubotin.news');
Route::get('/lubotin/news', [HarkivNewsController::class, 'lubotinHome'])->name('lubotin.line');
Route::get('/lubotin/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('lubotin.news');
Route::get('/merefa', [HarkivNewsController::class, 'merefaHome'])->name('merefa.news');
Route::get('/merefa/news', [HarkivNewsController::class, 'merefaHome'])->name('merefa.line');
Route::get('/merefa/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('merefa.news');
Route::get('/pervomayskiy', [HarkivNewsController::class, 'pervomayskiyHome'])->name('pervomayskiy.news');
Route::get('/pervomayskiy/news', [HarkivNewsController::class, 'pervomayskiyHome'])->name('pervomayskiy.line');
Route::get('/pervomayskiy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('pervomayskiy.news');
Route::get('/vovchansk', [HarkivNewsController::class, 'vovchanskHome'])->name('vovchansk.news');
Route::get('/vovchansk/news', [HarkivNewsController::class, 'vovchanskHome'])->name('vovchansk.line');
Route::get('/vovchansk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('vovchansk.news');
// Volynsk
Route::get('/kovel', [VolynskNewsController::class, 'kovelHome'])->name('kovel.news');
Route::get('/kovel/news', [VolynskNewsController::class, 'kovelHome'])->name('kovel.line');
Route::get('/kovel/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kovel.news');
Route::get('/lutsk', [VolynskNewsController::class, 'lutskHome'])->name('lutsk.news');
Route::get('/lutsk/news', [VolynskNewsController::class, 'lutskHome'])->name('lutsk.line');
Route::get('/lutsk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('lutsk.news');
Route::get('/novovolynsk', [VolynskNewsController::class, 'novovolynskHome'])->name('novovolynsk.news');
Route::get('/novovolynsk/news', [VolynskNewsController::class, 'novovolynskHome'])->name('novovolynsk.line');
Route::get('/novovolynsk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('novovolynsk.news');
Route::get('/volodymyr-volynskiy', [VolynskNewsController::class, 'volodymyrVolynskiyHome'])->name('volodymyr-volynskiy.news');
Route::get('/volodymyr-volynskiy/news', [VolynskNewsController::class, 'volodymyrVolynskiyHome'])->name('volodymyr-volynskiy.line');
Route::get('/volodymyr-volynskiy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('volodymyr-volynskiy.news');
// Zhytomyr
Route::get('/berdychiv', [ZhytomyrNewsController::class, 'berdychivHome'])->name('berdychiv.news');
Route::get('/berdychiv/news', [ZhytomyrNewsController::class, 'berdychivHome'])->name('berdychiv.line');
Route::get('/berdychiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('berdychiv.news');
Route::get('/korosten', [ZhytomyrNewsController::class, 'korostenHome'])->name('korosten.news');
Route::get('/korosten/news', [ZhytomyrNewsController::class, 'korostenHome'])->name('korosten.line');
Route::get('/korosten/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('korosten.news');
Route::get('/korostyshiv', [ZhytomyrNewsController::class, 'korostyshivHome'])->name('korostyshiv.news');
Route::get('/korostyshiv/news', [ZhytomyrNewsController::class, 'korostyshivHome'])->name('korostyshiv.line');
Route::get('/korostyshiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('korostyshiv.news');
Route::get('/malyn', [ZhytomyrNewsController::class, 'malynHome'])->name('malyn.news');
Route::get('/malyn/news', [ZhytomyrNewsController::class, 'malynHome'])->name('malyn.line');
Route::get('/malyn/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('malyn.news');
Route::get('/novohrad-volynskiy', [ZhytomyrNewsController::class, 'novohradVolynskiyHome'])->name('novohrad-volynskiy.news');
Route::get('/novohrad-volynskiy/news', [ZhytomyrNewsController::class, 'novohradVolynskiyHome'])->name('novohrad-volynskiy.line');
Route::get('/novohrad-volynskiy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('novohrad-volynskiy.news');
Route::get('/zhytomyr', [ZhytomyrNewsController::class, 'zhytomyrHome'])->name('zhytomyr.news');
Route::get('/zhytomyr/news', [ZhytomyrNewsController::class, 'zhytomyrHome'])->name('zhytomyr.line');
Route::get('/zhytomyr/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('zhytomyr.news');
// Zakarpatsk
Route::get('/beregove', [ZakarpatskNewsController::class, 'beregoveHome'])->name('beregove.news');
Route::get('/beregove/news', [ZakarpatskNewsController::class, 'beregoveHome'])->name('beregove.line');
Route::get('/beregove/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('beregove.news');
Route::get('/hust', [ZakarpatskNewsController::class, 'hustHome'])->name('hust.news');
Route::get('/hust/news', [ZakarpatskNewsController::class, 'hustHome'])->name('hust.line');
Route::get('/hust/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('hust.news');
Route::get('/mukachevo', [ZakarpatskNewsController::class, 'mukachevoHome'])->name('mukachevo.news');
Route::get('/mukachevo/news', [ZakarpatskNewsController::class, 'mukachevoHome'])->name('mukachevo.line');
Route::get('/mukachevo/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('mukachevo.news');
Route::get('/uzhhorod', [ZakarpatskNewsController::class, 'uzhhorodHome'])->name('uzhhorod.news');
Route::get('/uzhhorod/news', [ZakarpatskNewsController::class, 'uzhhorodHome'])->name('uzhhorod.line');
Route::get('/uzhhorod/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('uzhhorod.news');
Route::get('/vinohradiv', [ZakarpatskNewsController::class, 'vinohradivHome'])->name('vinohradiv.news');
Route::get('/vinohradiv/news', [ZakarpatskNewsController::class, 'vinohradivHome'])->name('vinohradiv.line');
Route::get('/vinohradiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('vinohradiv.news');
// Zaporizhzhia
Route::get('/berdyansk', [ZaporizhzhiaNewsController::class, 'berdyanskHome'])->name('berdyansk.news');
Route::get('/berdyansk/news', [ZaporizhzhiaNewsController::class, 'berdyanskHome'])->name('berdyansk.line');
Route::get('/berdyansk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('berdyansk.news');
Route::get('/dniprorudne', [ZaporizhzhiaNewsController::class, 'dniprorudneHome'])->name('dniprorudne.news');
Route::get('/dniprorudne/news', [ZaporizhzhiaNewsController::class, 'dniprorudneHome'])->name('dniprorudne.line');
Route::get('/dniprorudne/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('dniprorudne.news');
Route::get('/energodar', [ZaporizhzhiaNewsController::class, 'energodarHome'])->name('energodar.news');
Route::get('/energodar/news', [ZaporizhzhiaNewsController::class, 'energodarHome'])->name('energodar.line');
Route::get('/energodar/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('energodar.news');
Route::get('/melitopol', [ZaporizhzhiaNewsController::class, 'melitopolHome'])->name('melitopol.news');
Route::get('/melitopol/news', [ZaporizhzhiaNewsController::class, 'melitopolHome'])->name('melitopol.line');
Route::get('/melitopol/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('melitopol.news');
Route::get('/pology', [ZaporizhzhiaNewsController::class, 'pologyHome'])->name('pology.news');
Route::get('/pology/news', [ZaporizhzhiaNewsController::class, 'pologyHome'])->name('pology.line');
Route::get('/pology/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('pology.news');
Route::get('/tokmak', [ZaporizhzhiaNewsController::class, 'tokmakHome'])->name('tokmak.news');
Route::get('/tokmak/news', [ZaporizhzhiaNewsController::class, 'tokmakHome'])->name('tokmak.line');
Route::get('/tokmak/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('tokmak.news');
Route::get('/zaporizhzhia', [ZaporizhzhiaNewsController::class, 'zaporizhzhiaHome'])->name('zaporizhzhia.news');
Route::get('/zaporizhzhia/news', [ZaporizhzhiaNewsController::class, 'zaporizhzhiaHome'])->name('zaporizhzhia.line');
Route::get('/zaporizhzhia/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('zaporizhzhia.news');
// Ivano-Frankivsk
Route::get('/dolyna', [IvanoFrankivskNewsController::class, 'dolynaHome'])->name('dolyna.news');
Route::get('/dolyna/news', [IvanoFrankivskNewsController::class, 'dolynaHome'])->name('dolyna.line');
Route::get('/dolyna/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('dolyna.news');
Route::get('/ivano-frankivsk', [IvanoFrankivskNewsController::class, 'ivanoFrankivskHome'])->name('ivano-frankivsk.news');
Route::get('/ivano-frankivsk/news', [IvanoFrankivskNewsController::class, 'ivanoFrankivskHome'])->name('ivano-frankivsk.line');
Route::get('/ivano-frankivsk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('ivano-frankivsk.news');
Route::get('/kalush', [IvanoFrankivskNewsController::class, 'kalushHome'])->name('kalush.news');
Route::get('/kalush/news', [IvanoFrankivskNewsController::class, 'kalushHome'])->name('kalush.line');
Route::get('/kalush/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kalush.news');
Route::get('/kolomya', [IvanoFrankivskNewsController::class, 'kolomyaHome'])->name('kolomya.news');
Route::get('/kolomya/news', [IvanoFrankivskNewsController::class, 'kolomyaHome'])->name('kolomya.line');
Route::get('/kolomya/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kolomya.news');
Route::get('/nadvirna', [IvanoFrankivskNewsController::class, 'nadvirnaHome'])->name('nadvirna.news');
Route::get('/nadvirna/news', [IvanoFrankivskNewsController::class, 'nadvirnaHome'])->name('nadvirna.line');
Route::get('/nadvirna/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('nadvirna.news');
// Kirovograd
Route::get('/kropyvnytskiy', [KirovogradNewsController::class, 'kropyvnytskiyHome'])->name('kropyvnytskiy.news');
Route::get('/kropyvnytskiy/news', [KirovogradNewsController::class, 'kropyvnytskiyHome'])->name('kropyvnytskiy.line');
Route::get('/kropyvnytskiy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kropyvnytskiy.news');
Route::get('/olexandriya', [KirovogradNewsController::class, 'olexandriyaHome'])->name('olexandriya.news');
Route::get('/olexandriya/news', [KirovogradNewsController::class, 'olexandriyaHome'])->name('olexandriya.line');
Route::get('/olexandriya/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('olexandriya.news');
Route::get('/svitlovodsk', [KirovogradNewsController::class, 'svitlovodskHome'])->name('svitlovodsk.news');
Route::get('/svitlovodsk/news', [KirovogradNewsController::class, 'svitlovodskHome'])->name('svitlovodsk.line');
Route::get('/svitlovodsk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('svitlovodsk.news');
Route::get('/znamyanka', [KirovogradNewsController::class, 'znamyankaHome'])->name('znamyanka.news');
Route::get('/znamyanka/news', [KirovogradNewsController::class, 'znamyankaHome'])->name('znamyanka.line');
Route::get('/znamyanka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('znamyanka.news');
// Lviv
Route::get('/boryslav', [LvivNewsController::class, 'boryslavHome'])->name('boryslav.news');
Route::get('/boryslav/news', [LvivNewsController::class, 'boryslavHome'])->name('boryslav.line');
Route::get('/boryslav/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('boryslav.news');
Route::get('/brody', [LvivNewsController::class, 'brodyHome'])->name('brody.news');
Route::get('/brody/news', [LvivNewsController::class, 'brodyHome'])->name('brody.line');
Route::get('/brody/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('brody.news');
Route::get('/chervonograd', [LvivNewsController::class, 'chervonogradHome'])->name('chervonograd.news');
Route::get('/chervonograd/news', [LvivNewsController::class, 'chervonogradHome'])->name('chervonograd.line');
Route::get('/chervonograd/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('chervonograd.news');
Route::get('/drohobych', [LvivNewsController::class, 'drohobychHome'])->name('drohobych.news');
Route::get('/drohobych/news', [LvivNewsController::class, 'drohobychHome'])->name('drohobych.line');
Route::get('/drohobych/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('drohobych.news');
Route::get('/lviv', [LvivNewsController::class, 'lvivHome'])->name('lviv.news');
Route::get('/lviv/news', [LvivNewsController::class, 'lvivHome'])->name('lviv.line');
Route::get('/lviv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('lviv.news');
Route::get('/novoyavorivsk', [LvivNewsController::class, 'novoyavorivskHome'])->name('novoyavorivsk.news');
Route::get('/novoyavorivsk/news', [LvivNewsController::class, 'novoyavorivskHome'])->name('novoyavorivsk.line');
Route::get('/novoyavorivsk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('novoyavorivsk.news');
Route::get('/noviy-rozdil', [LvivNewsController::class, 'noviyRozdilHome'])->name('noviy-rozdil.news');
Route::get('/noviy-rozdil/news', [LvivNewsController::class, 'noviyRozdilHome'])->name('noviy-rozdil.line');
Route::get('/noviy-rozdil/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('noviy-rozdil.news');
Route::get('/sambir', [LvivNewsController::class, 'sambirHome'])->name('sambir.news');
Route::get('/sambir/news', [LvivNewsController::class, 'sambirHome'])->name('sambir.line');
Route::get('/sambir/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('sambir.news');
Route::get('/sokal', [LvivNewsController::class, 'sokalHome'])->name('sokal.news');
Route::get('/sokal/news', [LvivNewsController::class, 'sokalHome'])->name('sokal.line');
Route::get('/sokal/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('sokal.news');
Route::get('/stebnyk', [LvivNewsController::class, 'stebnykHome'])->name('stebnyk.news');
Route::get('/stebnyk/news', [LvivNewsController::class, 'stebnykHome'])->name('stebnyk.line');
Route::get('/stebnyk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('stebnyk.news');
Route::get('/striy', [LvivNewsController::class, 'striyHome'])->name('striy.news');
Route::get('/striy/news', [LvivNewsController::class, 'striyHome'])->name('striy.line');
Route::get('/striy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('striy.news');
Route::get('/truskavets', [LvivNewsController::class, 'truskavetsHome'])->name('truskavets.news');
Route::get('/truskavets/news', [LvivNewsController::class, 'truskavetsHome'])->name('truskavets.line');
Route::get('/truskavets/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('truskavets.news');
Route::get('/zolochiv', [LvivNewsController::class, 'zolochivHome'])->name('zolochiv.news');
Route::get('/zolochiv/news', [LvivNewsController::class, 'zolochivHome'])->name('zolochiv.line');
Route::get('/zolochiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('zolochiv.news');
// Mykolayiv
Route::get('/mykolayiv', [MykolayivNewsController::class, 'mykolayivHome'])->name('mykolayiv.news');
Route::get('/mykolayiv/news', [MykolayivNewsController::class, 'mykolayivHome'])->name('mykolayiv.line');
Route::get('/mykolayiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('mykolayiv.news');
Route::get('/pervomaisk', [MykolayivNewsController::class, 'pervomaiskHome'])->name('pervomaisk.news');
Route::get('/pervomaisk/news', [MykolayivNewsController::class, 'pervomaiskHome'])->name('pervomaisk.line');
Route::get('/pervomaisk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('pervomaisk.news');
Route::get('/voznesensk', [MykolayivNewsController::class, 'voznesenskHome'])->name('voznesensk.news');
Route::get('/voznesensk/news', [MykolayivNewsController::class, 'voznesenskHome'])->name('voznesensk.line');
Route::get('/voznesensk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('voznesensk.news');
Route::get('/yuzhnoukrainsk', [MykolayivNewsController::class, 'yuzhnoukrainskHome'])->name('yuzhnoukrainsk.news');
Route::get('/yuzhnoukrainsk/news', [MykolayivNewsController::class, 'yuzhnoukrainskHome'])->name('yuzhnoukrainsk.line');
Route::get('/yuzhnoukrainsk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('yuzhnoukrainsk.news');
// Poltava
Route::get('/hadiach', [PoltavaNewsController::class, 'hadiachHome'])->name('hadiach.news');
Route::get('/hadiach/news', [PoltavaNewsController::class, 'hadiachHome'])->name('hadiach.line');
Route::get('/hadiach/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('hadiach.news');
Route::get('/horishni-plavni', [PoltavaNewsController::class, 'horishniPlavniHome'])->name('horishni-plavni.news');
Route::get('/horishni-plavni/news', [PoltavaNewsController::class, 'horishniPlavniHome'])->name('horishni-plavni.line');
Route::get('/horishni-plavni/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('horishni-plavni.news');
Route::get('/kremenchuk', [PoltavaNewsController::class, 'kremenchukHome'])->name('kremenchuk.news');
Route::get('/kremenchuk/news', [PoltavaNewsController::class, 'kremenchukHome'])->name('kremenchuk.line');
Route::get('/kremenchuk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kremenchuk.news');
Route::get('/lubny', [PoltavaNewsController::class, 'lubnyHome'])->name('lubny.news');
Route::get('/lubny/news', [PoltavaNewsController::class, 'lubnyHome'])->name('lubny.line');
Route::get('/lubny/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('lubny.news');
Route::get('/myrhorod', [PoltavaNewsController::class, 'myrhorodHome'])->name('myrhorod.news');
Route::get('/myrhorod/news', [PoltavaNewsController::class, 'myrhorodHome'])->name('myrhorod.line');
Route::get('/myrhorod/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('myrhorod.news');
Route::get('/poltava', [PoltavaNewsController::class, 'poltavaHome'])->name('poltava.news');
Route::get('/poltava/news', [PoltavaNewsController::class, 'poltavaHome'])->name('poltava.line');
Route::get('/poltava/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('poltava.news');
// Rivne
Route::get('/dubno', [RivneNewsController::class, 'dubnoHome'])->name('dubno.news');
Route::get('/dubno/news', [RivneNewsController::class, 'dubnoHome'])->name('dubno.line');
Route::get('/dubno/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('dubno.news');
Route::get('/kostopil', [RivneNewsController::class, 'kostopilHome'])->name('kostopil.news');
Route::get('/kostopil/news', [RivneNewsController::class, 'kostopilHome'])->name('kostopil.line');
Route::get('/kostopil/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kostopil.news');
Route::get('/rivne', [RivneNewsController::class, 'rivneHome'])->name('rivne.news');
Route::get('/rivne/news', [RivneNewsController::class, 'rivneHome'])->name('rivne.line');
Route::get('/rivne/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('rivne.news');
Route::get('/sarny', [RivneNewsController::class, 'sarnyHome'])->name('sarny.news');
Route::get('/sarny/news', [RivneNewsController::class, 'sarnyHome'])->name('sarny.line');
Route::get('/sarny/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('sarny.news');
Route::get('/varash', [RivneNewsController::class, 'varashHome'])->name('varash.news');
Route::get('/varash/news', [RivneNewsController::class, 'varashHome'])->name('varash.line');
Route::get('/varash/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('varash.news');
Route::get('/zdolbuniv', [RivneNewsController::class, 'zdolbunivHome'])->name('zdolbuniv.news');
Route::get('/zdolbuniv/news', [RivneNewsController::class, 'zdolbunivHome'])->name('zdolbuniv.line');
Route::get('/zdolbuniv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('zdolbuniv.news');
// Sumy
Route::get('/gluhiv', [SumyNewsController::class, 'gluhivHome'])->name('gluhiv.news');
Route::get('/gluhiv/news', [SumyNewsController::class, 'gluhivHome'])->name('gluhiv.line');
Route::get('/gluhiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('gluhiv.news');
Route::get('/konotop', [SumyNewsController::class, 'konotopHome'])->name('konotop.news');
Route::get('/konotop/news', [SumyNewsController::class, 'konotopHome'])->name('konotop.line');
Route::get('/konotop/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('konotop.news');
Route::get('/krolevets', [SumyNewsController::class, 'krolevetsHome'])->name('krolevets.news');
Route::get('/krolevets/news', [SumyNewsController::class, 'krolevetsHome'])->name('krolevets.line');
Route::get('/krolevets/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('krolevets.news');
Route::get('/lebedyn', [SumyNewsController::class, 'lebedynHome'])->name('lebedyn.news');
Route::get('/lebedyn/news', [SumyNewsController::class, 'lebedynHome'])->name('lebedyn.line');
Route::get('/lebedyn/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('lebedyn.news');
Route::get('/ohtyrka', [SumyNewsController::class, 'ohtyrkaHome'])->name('ohtyrka.news');
Route::get('/ohtyrka/news', [SumyNewsController::class, 'ohtyrkaHome'])->name('ohtyrka.line');
Route::get('/ohtyrka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('ohtyrka.news');
Route::get('/romny', [SumyNewsController::class, 'romnyHome'])->name('romny.news');
Route::get('/romny/news', [SumyNewsController::class, 'romnyHome'])->name('romny.line');
Route::get('/romny/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('romny.news');
Route::get('/shostka', [SumyNewsController::class, 'shostkaHome'])->name('shostka.news');
Route::get('/shostka/news', [SumyNewsController::class, 'shostkaHome'])->name('shostka.line');
Route::get('/shostka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('shostka.news');
Route::get('/sumy', [SumyNewsController::class, 'sumyHome'])->name('sumy.news');
Route::get('/sumy/news', [SumyNewsController::class, 'sumyHome'])->name('sumy.line');
Route::get('/sumy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('sumy.news');
Route::get('/trostyanets', [SumyNewsController::class, 'trostyanetsHome'])->name('trostyanets.news');
Route::get('/trostyanets/news', [SumyNewsController::class, 'trostyanetsHome'])->name('trostyanets.line');
Route::get('/trostyanets/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('trostyanets.news');
// Ternopil
Route::get('/chortkiv', [TernopilNewsController::class, 'chortkivHome'])->name('chortkiv.news');
Route::get('/chortkiv/news', [TernopilNewsController::class, 'chortkivHome'])->name('chortkiv.line');
Route::get('/chortkiv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('chortkiv.news');
Route::get('/kremenets', [TernopilNewsController::class, 'kremenetsHome'])->name('kremenets.news');
Route::get('/kremenets/news', [TernopilNewsController::class, 'kremenetsHome'])->name('kremenets.line');
Route::get('/kremenets/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kremenets.news');
Route::get('/ternopil', [TernopilNewsController::class, 'ternopilHome'])->name('ternopil.news');
Route::get('/ternopil/news', [TernopilNewsController::class, 'ternopilHome'])->name('ternopil.line');
Route::get('/ternopil/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('ternopil.news');
// Kherson
Route::get('/henichesk', [KhersonNewsController::class, 'henicheskHome'])->name('henichesk.news');
Route::get('/henichesk/news', [KhersonNewsController::class, 'henicheskHome'])->name('henichesk.line');
Route::get('/henichesk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('henichesk.news');
Route::get('/kahovka', [KhersonNewsController::class, 'kahovkaHome'])->name('kahovka.news');
Route::get('/kahovka/news', [KhersonNewsController::class, 'kahovkaHome'])->name('kahovka.line');
Route::get('/kahovka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kahovka.news');
Route::get('/kherson', [KhersonNewsController::class, 'khersonHome'])->name('kherson.news');
Route::get('/kherson/news', [KhersonNewsController::class, 'khersonHome'])->name('kherson.line');
Route::get('/kherson/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kherson.news');
Route::get('/nova-kakhovka', [KhersonNewsController::class, 'novaKakhovkaHome'])->name('nova-kakhovka.news');
Route::get('/nova-kakhovka/news', [KhersonNewsController::class, 'novaKakhovkaHome'])->name('nova-kakhovka.line');
Route::get('/nova-kakhovka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('nova-kakhovka.news');
Route::get('/oleshki', [KhersonNewsController::class, 'oleshkiHome'])->name('oleshki.news');
Route::get('/oleshki/news', [KhersonNewsController::class, 'oleshkiHome'])->name('oleshki.line');
Route::get('/nova-kakhovka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('nova-kakhovka.news');
Route::get('/skadovsk', [KhersonNewsController::class, 'skadovskHome'])->name('skadovsk.news');
Route::get('/skadovsk/news', [KhersonNewsController::class, 'skadovskHome'])->name('skadovsk.line');
Route::get('/skadovsk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('skadovsk.news');
// Hmelnytskiy
Route::get('/hmelnytskiy', [HmelnytskiyNewsController::class, 'hmelnytskiyHome'])->name('hmelnytskiy.news');
Route::get('/hmelnytskiy/news', [HmelnytskiyNewsController::class, 'hmelnytskiyHome'])->name('hmelnytskiy.line');
Route::get('/hmelnytskiy/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('hmelnytskiy.news');
Route::get('/kamyanets-podilsky', [HmelnytskiyNewsController::class, 'kamyanetsPodilskyHome'])->name('kamyanets-podilsky.news');
Route::get('/kamyanets-podilsky/news', [HmelnytskiyNewsController::class, 'kamyanetsPodilskyHome'])->name('kamyanets-podilsky.line');
Route::get('/kamyanets-podilsky/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('kamyanets-podilsky.news');
Route::get('/krasyliv', [HmelnytskiyNewsController::class, 'krasylivHome'])->name('krasyliv.news');
Route::get('/krasyliv/news', [HmelnytskiyNewsController::class, 'krasylivHome'])->name('krasyliv.line');
Route::get('/krasyliv/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('krasyliv.news');
Route::get('/netishin', [HmelnytskiyNewsController::class, 'netishinHome'])->name('netishin.news');
Route::get('/netishin/news', [HmelnytskiyNewsController::class, 'netishinHome'])->name('netishin.line');
Route::get('/netishin/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('netishin.news');
Route::get('/polonne', [HmelnytskiyNewsController::class, 'polonneHome'])->name('polonne.news');
Route::get('/polonne/news', [HmelnytskiyNewsController::class, 'polonneHome'])->name('polonne.line');
Route::get('/polonne/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('polonne.news');
Route::get('/shepetivka', [HmelnytskiyNewsController::class, 'shepetivkaHome'])->name('shepetivka.news');
Route::get('/shepetivka/news', [HmelnytskiyNewsController::class, 'shepetivkaHome'])->name('shepetivka.line');
Route::get('/shepetivka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('shepetivka.news');
Route::get('/slavuta', [HmelnytskiyNewsController::class, 'slavutaHome'])->name('slavuta.news');
Route::get('/slavuta/news', [HmelnytskiyNewsController::class, 'slavutaHome'])->name('slavuta.line');
Route::get('/slavuta/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('slavuta.news');
Route::get('/starokostyntynivka', [HmelnytskiyNewsController::class, 'starokostyntynivkaHome'])->name('starokostyntynivka.news');
Route::get('/starokostyntynivka/news', [HmelnytskiyNewsController::class, 'starokostyntynivkaHome'])->name('starokostyntynivka.line');
Route::get('/starokostyntynivka/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('starokostyntynivka.news');
Route::get('/volochysk', [HmelnytskiyNewsController::class, 'volochyskHome'])->name('volochysk.news');
Route::get('/volochysk/news', [HmelnytskiyNewsController::class, 'volochyskHome'])->name('volochysk.line');
Route::get('/volochysk/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('volochysk.news');

// Dnipro
Route::get('/dnipro', [DniproNewsController::class, 'dniproHome'])->name('dnipro.news');
Route::get('/kamianske', [DniproNewsController::class, 'kamianskeHome'])->name('kamianske.news');
Route::get('/kryvyi-rih', [DniproNewsController::class, 'kryvyiRihHome'])->name('kryvyi-rih.news');
Route::get('/marganets', [DniproNewsController::class, 'marganetsHome'])->name('marganets.news');
Route::get('/nikopol', [DniproNewsController::class, 'nikopolHome'])->name('nikopol.news');
Route::get('/novomoskovsk', [DniproNewsController::class, 'novomoskovskHome'])->name('novomoskovsk.news');
Route::get('/pavlograd', [DniproNewsController::class, 'pavlogradHome'])->name('pavlograd.news');
Route::get('/pershotravensk', [DniproNewsController::class, 'pershotravenskHome'])->name('pershotravensk.news');
Route::get('/pokrov', [DniproNewsController::class, 'pokrovHome'])->name('pokrov.news');
Route::get('/pyatihatky', [DniproNewsController::class, 'pyatihatkyHome'])->name('pyatihatky.news');
Route::get('/sinelnikovo', [DniproNewsController::class, 'sinelnikovoHome'])->name('sinelnikovo.news');
Route::get('/ternivka', [DniproNewsController::class, 'ternivkaHome'])->name('ternivka.news');
Route::get('/vilnohorsk', [DniproNewsController::class, 'vilnohorskHome'])->name('vilnohorsk.news');
Route::get('/zhovti-vody', [DniproNewsController::class, 'zhovtiVodyHome'])->name('zhovti-vody.news');

Route::get('/dnipro/news/', [DniproNewsController::class, 'dniproLine'])->name('dnipro.line');
Route::get('/kamianske/news/', [DniproNewsController::class, 'kamianskeLine'])->name('kamianske.line');
Route::get('/kryvyi-rih/news/', [DniproNewsController::class, 'kryvyiRihLine'])->name('kryvyi-rih.line');
Route::get('/marganets/news/', [DniproNewsController::class, 'marganetsLine'])->name('marganets.line');
Route::get('/nikopol/news/', [DniproNewsController::class, 'nikopolLine'])->name('nikopol.line');
Route::get('/novomoskovsk/news/', [DniproNewsController::class, 'novomoskovskLine'])->name('novomoskovsk.line');
Route::get('/pavlograd/news/', [DniproNewsController::class, 'pavlogradLine'])->name('pavlograd.line');
Route::get('/pershotravensk/news/', [DniproNewsController::class, 'pershotravenskLine'])->name('pershotravensk.line');
Route::get('/pokrov/news/', [DniproNewsController::class, 'pokrovLine'])->name('pokrov.line');
Route::get('/pyatihatky/news/', [DniproNewsController::class, 'pyatihatkyLine'])->name('pyatihatky.line');
Route::get('/sinelnikovo/news/', [DniproNewsController::class, 'sinelnikovoLine'])->name('sinelnikovo.line');
Route::get('/ternivka/news/', [DniproNewsController::class, 'ternivkaLine'])->name('ternivka.line');
Route::get('/vilnohorsk/news/', [DniproNewsController::class, 'vilnohorskLine'])->name('vilnohorsk.line');
Route::get('/zhovti-vody/news/', [DniproNewsController::class, 'zhovtiVodyLine'])->name('zhovti-vody.line');

Route::get('/dnipro/news/{url}', [DniproNewsController::class, 'dniproNews'])->name('dnipro.news');
Route::get('/kamianske/news/{url}', [DniproNewsController::class, 'kamianskeNews'])->name('kamianske.news');
Route::get('/kryvyi-rih/news/{url}', [DniproNewsController::class, 'kryvyiRihNews'])->name('kryvyi-rih.news');
Route::get('/marganets/news/{url}', [DniproNewsController::class, 'marganetsNews'])->name('marganets.news');
Route::get('/nikopol/news/{url}', [DniproNewsController::class, 'nikopolNews'])->name('nikopol.news');
Route::get('/novomoskovsk/news/{url}', [DniproNewsController::class, 'novomoskovskNews'])->name('novomoskovsk.news');
Route::get('/pavlograd/news/{url}', [DniproNewsController::class, 'pavlogradNews'])->name('pavlograd.news');
Route::get('/pershotravensk/news/{url}', [DniproNewsController::class, 'pershotravenskNews'])->name('pershotravensk.news');
Route::get('/pokrov/news/{url}', [DniproNewsController::class, 'pokrovNews'])->name('pokrov.news');
Route::get('/pyatihatky/news/{url}', [DniproNewsController::class, 'pyatihatkyNews'])->name('pyatihatky.news');
Route::get('/sinelnikovo/news/{url}', [DniproNewsController::class, 'sinelnikovoNews'])->name('sinelnikovo.news');
Route::get('/ternivka/news/{url}', [DniproNewsController::class, 'ternivkaNews'])->name('ternivka.news');
Route::get('/vilnohorsk/news/{url}', [DniproNewsController::class, 'vilnohorskNews'])->name('vilnohorsk.news');
Route::get('/zhovti-vody/news/{url}', [DniproNewsController::class, 'zhovtiVodyNews'])->name('zhovti-vody.news');

// Odessa
Route::get('/bilgorod-dnistrovsky/news/', [OdesaNewsController::class, 'bilgorodDnistrovskyLine'])->name('bilgorod.line');
Route::get('/chornomorsk/news/', [OdesaNewsController::class, 'chornomorskLine'])->name('chornomorsk.line');
Route::get('/izmail/news/', [LineNewsController::class, 'index'])->name('izmail.line');
Route::get('/kiliya/news/', [OdesaNewsController::class, 'kiliyaLine'])->name('kiliya.line');
Route::get('/odesa/news/', [OdesaNewsController::class, 'odesaLine'])->name('odesa.line');
Route::get('/podilsk/news/', [OdesaNewsController::class, 'podilskLine'])->name('podilsk.line');
Route::get('/teplodar/news/', [OdesaNewsController::class, 'teplodarLine'])->name('teplodar.line');
Route::get('/youzhne/news/', [OdesaNewsController::class, 'youzhneLine'])->name('youzhne.line');

// Route::get('//news/', [OdesaNewsController::class, 'Line'])->name('.line');

Route::get('/bilgorod-dnistrovsky/news/{url}', [OdesaNewsController::class, 'bilgorodDnistrovskyNews'])->name('bilgorod.news');
Route::get('/chornomorsk/news/{url}', [OdesaNewsController::class, 'chornomorskNews'])->name('chornomorsk.news');
Route::get('/izmail/news/{url}', [OdesaNewsController::class, 'izmailNews'])->name('izmail.news');
Route::get('/kiliya/news/{url}', [OdesaNewsController::class, 'kiliyaNews'])->name('kiliya.news');
Route::get('/odesa/news/{url}', [OdesaNewsController::class, 'odesaNews'])->name('odesa.news');
Route::get('/podilsk/news/{url}', [OdesaNewsController::class, 'podilskNews'])->name('podilsk.news');
Route::get('/teplodar/news/{url}', [OdesaNewsController::class, 'teplodarNews'])->name('teplodar.news');
Route::get('/youzhne/news/{url}', [OdesaNewsController::class, 'youzhneNews'])->name('youzhne.news');
// Route::get('//news/{url}', [OdesaNewsController::class, 'News'])->name('.news');

Route::get('/teplodar/search', [SearchController::class, 'teplodarSearch'])->name('teplodar.search');

